AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 80
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/LambdaCall:
  Enabled: false
